=== liu-weida/Sorbonne-CS-Master-Playbook-No-Warranty/DAC/mlbda/tme/tme6/xschema/base-contrainte.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="base">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="restaurant" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <!-- c1 -->
              <xs:element name="fermeture" type="xs:string" minOccurs="0"/>
              <xs:element name="menu" minOccurs="2" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="nom" type="xs:string" use="required"/>
                  <xs:attribute name="prix" type="xs:int" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            
              <!-- c2 -->
              <xs:element name="plusBeauMonument" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                
                  <!-- c3 -->
                  <xs:attribute name="nom" type="xs:string" use="required"/>
                  <xs:attribute name="tarif" type="xs:int" use="required"/>
                  
                </xs:complexType>
              </xs:element>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== liu-weida/Sorbonne-CS-Master-Playbook-No-Warranty/DAC/S1/mlbda/tme/tme6/xschema/base-contrainte.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="base-contrainte.xsd">

  <restaurant nom="la tour d'argent" etoile="3" ville="Paris">
    <fermeture>dimanche et lundi</fermeture>
    <menu nom="buffet" prix="200"/>
    <menu nom="gourmet" prix="300"/>
  </restaurant>

  <ville nom="Paris" departement="75">
    <plusBeauMonument nom="tour Eiffel" tarif="30"/>
  </ville>

  <restaurant nom="chez Bocuse" etoile="2" ville="Lyon">
    <fermeture>dimanche</fermeture>
    <menu nom="specialites lyonnaises" prix="200"/>
    <menu nom="vegetarien" prix="299"/>
  </restaurant>

  <restaurant nom="MacDo" etoile="0" ville="Avignon">
    <menu nom="standard" prix="35"/>
    <menu nom="enfant" prix="20"/>
    <menu nom="big" prix="49"/>
  </restaurant>

  <ville nom="Lyon" departement="69">
  </ville>

  <ville nom="Avignon" departement="84">
    <plusBeauMonument nom="le pont" tarif="0"/>
  </ville>

  <restaurant nom="Les 4 saisons" etoile="1" ville="Paris">
     <fermeture>mardi</fermeture>
       <menu nom="assiette printaniere" prix="50"/>
       <menu nom="salade d'ete" prix="30"/>
       <menu nom="menu d'automne" prix="150"/>
       <menu nom="menu d'hiver" prix="99"/>
  </restaurant>

  <ville nom="Brest" departement="29">
     <plusBeauMonument nom="oceanopolis" tarif="95"/>
  </ville>


</base>
